pc=float(input("Precio cerveza "))
pv=float(input("Precio vino "))
pp=float(input("Precio patatas fritas "))
c=int(input("Cuántas cervezas? "))
v=int(input("Cuántos vinos? "))
p=int(input("Cuántas patatas fritas? "))
tc=float(pc*c)
tv=float(pv*v)
tp=float(pp*p)
total= float(tc+tv+tp)

print("--------------------------")
print("Total compra")
print("--------------------------")
print("Cerveza ", c, tc)
print("Vino ", v, tv)
print("Patatas fritas ", p, tp)
print("Total ", total)